version: '3.9'
services:

  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 28Jp7hs5GqEAcmWb
    ports:
      - 5432:5432

  pgadmin4:
    image: dpage/pgadmin4:latest
    ports:
      - 8137:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    links:
      - postgresql
    depends_on:
      - postgresql
